
import os
import datetime
import psycopg2
from psycopg2 import sql
from dotenv import load_dotenv

load_dotenv()

# Database connection details
DB_NAME = os.getenv("DB_NAME")
DB_USER = os.getenv("DB_USER")
DB_PASS = os.getenv("DB_PASS")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")

def get_connection():
    return psycopg2.connect(
        dbname=DB_NAME,
        user=DB_USER,
        password=DB_PASS,
        host=DB_HOST,
        port=DB_PORT
    )

def format_value(value):
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, datetime.datetime):
        return f"'{value.strftime('%Y-%m-%d %H:%M:%S.%f%z')}'"
    if isinstance(value, datetime.date):
        return f"'{value.strftime('%Y-%m-%d')}'"
    # Basic escaping for strings: replace single quotes with two single quotes
    # Also handle backslashes if standard_conforming_strings is off, but standard SQL escapes ' with ''
    escaped = str(value).replace("'", "''")
    return f"'{escaped}'"

def export_data(output_file="data_export.sql"):
    conn = get_connection()
    cursor = conn.cursor()

    # Get all tables
    cursor.execute("""
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_type = 'BASE TABLE'
        ORDER BY table_name;
    """)
    tables = [row[0] for row in cursor.fetchall()]

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("-- Data Export generated by AI Agent\n")
        f.write(f"-- Date: {datetime.datetime.now()}\n\n")

        for table in tables:
            print(f"Exporting {table}...")
            f.write(f"-- Data for table: {table}\n")
            
            # Get columns
            cursor.execute(f"SELECT column_name FROM information_schema.columns WHERE table_name = '{table}' ORDER BY ordinal_position")
            columns = [row[0] for row in cursor.fetchall()]
            col_list = ", ".join(f'"{c}"' for c in columns)
            
            # Get data
            cursor.execute(sql.SQL("SELECT * FROM {}").format(sql.Identifier(table)))
            rows = cursor.fetchall()
            
            for row in rows:
                values = [format_value(val) for val in row]
                val_list = ", ".join(values)
                insert_stmt = f"INSERT INTO \"{table}\" ({col_list}) VALUES ({val_list});\n"
                f.write(insert_stmt)
            
            f.write("\n")
            
    print(f"Export completed to {output_file}")
    cursor.close()
    conn.close()

if __name__ == "__main__":
    export_data()
