
import os
import datetime
import psycopg2
from psycopg2 import sql
from dotenv import load_dotenv

load_dotenv()

# Database connection details
DB_NAME = os.getenv("DB_NAME")
DB_USER = os.getenv("DB_USER")
DB_PASS = os.getenv("DB_PASS")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")

def get_connection():
    return psycopg2.connect(
        dbname=DB_NAME,
        user=DB_USER,
        password=DB_PASS,
        host=DB_HOST,
        port=DB_PORT
    )

def format_value(value):
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, datetime.datetime):
        return f"'{value.strftime('%Y-%m-%d %H:%M:%S.%f%z')}'"
    if isinstance(value, datetime.date):
        return f"'{value.strftime('%Y-%m-%d')}'"
    # Basic escaping for strings: replace single quotes with two single quotes
    # Also handle backslashes if standard_conforming_strings is off, but standard SQL escapes ' with ''
    escaped = str(value).replace("'", "''")
    return f"'{escaped}'"

def export_data(output_file="data_export.sql"):
    conn = get_connection()
    cursor = conn.cursor()

    # Define table priority (parents first, children last)
    # Higher priority (lower index) tables are exported first.
    # Tables not listed here will be sorted alphabetically after these.
    # Urutan prioritas agar parent di-insert dulu (hindari FK error saat import)
    PRIORITY_TABLES = [
        # Portal master (wilayah dan sekolah)
        "portal_kecamatan",
        "portal_kelurahan",
        "portal_schools",
        "portal_rooms",
        "portal_aspects",
        "portal_school_rooms",
        # Kelas & seksi
        "school_classes",
        "sections",
        # Pengguna (butuh sekolah/kelas/seksi sudah ada)
        "dashboard_users",
        "web_users",
        "telegram_users",
        # Portal periode & assessment
        "portal_assessment_periods",
        "portal_assessments",
        "portal_assessment_room_details",
        "portal_assessment_scores",
        "portal_assessment_photos",
        # Aktivitas & akses
        "portal_activity_logs",
        "user_kecamatan",
        "staff_school_assignments",
        "school_classrooms",
        # Monev
        "monev_teams",
        "monev_team_members",
        "monev_team_member_requests",
        # Laporan & chat
        "chat_logs",
        "chat_feedback",
        "bullying_reports",
        "bullying_report_events",
        "psych_reports",
        "corruption_reports",
        "notifications",
        # Lain-lain
        "students",
        "twitter_worker_logs",
    ]

    # Get all tables
    cursor.execute("""
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_type = 'BASE TABLE'
    """)
    all_tables = [row[0] for row in cursor.fetchall()]

    # Sort tables: Priority list first, then others alphabetically
    tables = []
    
    # Add priority tables that exist in the database
    for p_table in PRIORITY_TABLES:
        if p_table in all_tables:
            tables.append(p_table)
            all_tables.remove(p_table)
            
    # Add remaining tables (sorted alphabetically)
    tables.extend(sorted(all_tables))

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("-- Data Export generated by AI Agent\n")
        f.write(f"-- Date: {datetime.datetime.now()}\n\n")

        for table in tables:
            print(f"Exporting {table}...")
            f.write(f"-- Data for table: {table}\n")
            
            # Get columns
            cursor.execute(f"SELECT column_name FROM information_schema.columns WHERE table_name = '{table}' ORDER BY ordinal_position")
            columns = [row[0] for row in cursor.fetchall()]
            col_list = ", ".join(f'"{c}"' for c in columns)
            
            # Get data
            cursor.execute(sql.SQL("SELECT * FROM {}").format(sql.Identifier(table)))
            rows = cursor.fetchall()
            
            for row in rows:
                values = [format_value(val) for val in row]
                val_list = ", ".join(values)
                insert_stmt = f"INSERT INTO \"{table}\" ({col_list}) VALUES ({val_list});\n"
                f.write(insert_stmt)
            
            f.write("\n")
            
    print(f"Export completed to {output_file}")
    cursor.close()
    conn.close()

if __name__ == "__main__":
    export_data()
